accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

share/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.views.generic import RedirectView
# from share.share import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sns.urls')),
    # ACCOUNTSアプリへのルーティングになっている
    path('accounts/', include('accounts.urls')),
    # Djangoの認証用のVIEWを呼び出す
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='/sns/')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sns/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.IndexList.as_view(), name='index'),
    path('new/', views.new, name='new'),
    path('article/all/', views.ArticleList.as_view(), name='article_all'),
    path('article/<int:pk>/', views.view_article, name="view_article"),
    path("article/<int:pk>/edit/", views.edit, name="edit"),
    path('article/<int:pk>/delete/', views.delete, name="delete"),
    path("article/<int:pk>/like/", views.like, name="like"),
    path("api/like/<int:pk>/", views.api_like, name="api_like"),
]

accounts/models.py
from django.db import models

# Create your models here.

sns/models.py
from django.db import models


class Article(models.Model):
    DoesNotExist = None
    objects = None
    title = models.CharField(max_length=30)
    text = models.TextField()
    posted_at = models.DateTimeField(auto_now_add=True)
    last_modify = models.DateTimeField(auto_now=True)
    like = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class Comment(models.Model):
    text = models.TextField()
    posted_at = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(to=Article, related_name='comments', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='share/images', blank=True, null=True)

    def __str__(self):
        return self.text


# class Image(models.Model):
#     picture = models.ImageField(upload_to='images/')
#
#     def __str__(self):
#         return self.picture
# class Photo(models.Model):
#     image = models.ImageField(upload_to='myapp')

sns/forms.py
from django import forms
from .models import Comment


class SearchForm(forms.Form):
    keyword = forms.CharField(max_length=100)


class CommentForm(forms.ModelForm):
    file = forms.FileField(
        label=''
    )

    class Meta:
        model = Comment
        fields = ('text', 'image')

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

sns/views.py
from django.shortcuts import render, redirect
from django.http import Http404
from django.http.response import JsonResponse
from . import models
from .models import Article
from django.contrib.auth.decorators import login_required
from .forms import CommentForm
from django.views.generic import ListView
from django.db.models import Q


class IndexList(ListView):
    template_name = 'sns/index.html'
    queryset = Article.objects.order_by('-posted_at')
    paginate_by = 5
    model = Article

    def get_queryset(self):
        q_word = self.request.GET.get('query')

        if q_word:
            object_list = Article.objects.filter(
                Q(title__icontains=q_word) | Q(text__icontains=q_word)
            )
        else:
            object_list = Article.objects.all()
        return object_list


@login_required
def new(request):
    template_name = "sns/new.html"
    if request.method == "POST":
        models.Article.objects.create(
            title=request.POST["title"],
            text=request.POST["text"]
        )
        # return redirect(index)
        return redirect(IndexList)
    return render(request, template_name)
    # return redirect(article_all)



class ArticleList(ListView):
    template_name = "sns/article_all.html"
    queryset = Article.objects.order_by('-posted_at')
    model = Article


def view_article(request, pk):
    comment = CommentForm(request.GET)
    template_name = 'sns/view_article.html'
    try:
        article = models.Article.objects.get(pk=pk)
    except models.Article.DoesNotExist:
        raise Http404
    if request.method == "POST":
        models.Comment.objects.create(text=request.POST["text"], article=article)
    context = {
        "article": article,
        "comment": comment
    }
    return render(request, template_name, context)


@login_required
def edit(request, pk):
    template_name = "sns/edit.html"
    try:
        article = models.Article.objects.get(pk=pk)
    except models.Article.DoesNotExist:
        raise Http404
    if request.method == "POST":
        article.title = request.POST["title"]
        article.text = request.POST["text"]
        article.save()
        return redirect(view_article, pk)
    context = {"article": article}
    return render(request, template_name, context)


@login_required
def delete(request, pk):
    try:
        article = models.Article.objects.get(pk=pk)
    except models.Article.DoesNotExist:
        raise Http404
    article.delete()
    # return redirect(article_all)
    return redirect(ArticleList)


def like(request, pk):
    try:
        article = models.Article.objects.get(pk=pk)
    except models.Article.DoesNotExist:
        raise Http404
    article.like += 1
    article.save()
    return redirect(view_article, pk)


def api_like(request, pk):
    try:
        article = models.Article.objects.get(pk=pk)
    except models.Article.DoesNotExist:
        raise Http404
    article.like += 1
    article.save()
    return JsonResponse({"like": article.like})

accounts/templates/accounts/signup.html
{% extends 'layout.html' %}

{% block content %}
<h1>Sign up</h1>
<section class="common-form">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign up</button>
    </form>
</section>
{% endblock %}

sns/templates/sns/article_all.html
{% extends 'layout.html' %}
{% block content %}
  <div class="viewall-contents">
    <h3>タイトル一覧</h3>
<!--    {% for article in articles %}-->
<!--    <p class="topics"><a href="{% url 'view_article' article.pk %}">{{ article.title }}</a></p>-->
<!--    <a href="{% url 'edit' article.pk %}" class="btn btn-border"><span>編集</span></a>-->
<!--    <a href="{% url 'delete' article.pk %}" class="btn btn-border"><span>削除</span></a>-->
<!--    {% endfor %}-->
    {% for article in object_list %}
    <p class="topics">
      <a href="{% url 'view_article' article.pk %}">
        {{ article.title }}
      </a>
    </p>
    {% endfor %}
    <div>
        <a href="{% url 'index' %}" class="btn btn-border"><span class="toppage">トップページへ</span></a>
    </div>
  </div>
{% endblock %}

sns/templates/sns/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
<head>
<meta charset="utf-8">
<title>あんにょん</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!--    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'>-->
<!--    <style>body {padding-top: 80px;}</style>-->
<link rel="stylesheet" href="{% static 'css/base.css' %}">
<link rel="stylesheet" href="{% static 'css/btn.css' %}">
<link rel="stylesheet" href="{% static 'css/topics.css' %}">
<link rel="stylesheet" href="{% static 'css/textbox.css' %}">
<link rel="stylesheet" href="{% static 'css/comment.css' %}">
<link rel="stylesheet" href="{% static 'css/search.css' %}">
</head>
<body>

<!--                    header                    -->

<div class='header'>
  <nav>
    <ul class="nav-items">
      <a href='{% url "index" %}' class="logo" ><h1>あんにょん</h1></a>
      {% if user.is_authenticated %}
      <li class="nav-item">
        <span class=''>{{ user }} - </span>
      </li>
      <li class="nav-item">
        <a href='{% url "logout" %}' class='logout'><i class="fas fa-sign-out-alt"></i> Logout</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a href='{% url "login" %}' class='login'><i class="fas fa-sign-in-alt"></i> Login</a>
      </li>
      <li class="nav-item">
        <a href='{% url "accounts:signup" %}' class='signup'><i class="fas fa-user-plus"></i> Sign up</a>
      </li>
      {% endif %}
      <li class="nav-item">
        <form id="form2" action="" method="get">
          <input id="sbox2" id="s" name="s" value="{{ request.GET.query }}" type="text" placeholder="検索ワードを入力">
         <!-- <button type="submit" id="sbtn2"><i class="fas fa-search"></i></button> -->
          <input type="submit" value="検索">
        </form>
      </li>
    </ul>
  </nav>
</div>

<!--                    main                    -->

<div class="main">
  {% block content %}
  {% endblock %}
</div>

<!--                    footer                    -->

<div class="footer">
  <div class="container">
    <nav>
      <ul>
        <li><a href=""> - About</a></li>
        <li><a href=""> - Contact</a></li>
      </ul>
    </nav>
    <p>@2020 made in ShogoIkeda</p>
  </div>
</div>
</body>
</html>

sns/templates/sns/edit.html
{% extends './base.html' %}

{% block content %}
  <div class="edit-contents">
    <h3>編集</h3>
    <form action="" method="post">
        {% csrf_token %}
        <p><label for="title_input">Title</label></p>
        <p><input type="text" name="title" id="title_input" value="{{ article.title }}"></p>
        <p><label for="text_area">Text</label></p>
        <p><textarea name="text" id="text_area" cols="30" rows="10">{{ article.text }}</textarea></p>
        <p><button type="submit">Update</button></p>
    </form>
    <a href="{% url 'index' %}" class="btn btn-border"><span class="toppage">トップページへ</span></a>
    <a href="{% url 'view_article' article.pk%}" class="btn btn-border"><span class="toppage">キャンセル</span></a>
  </div>
{% endblock %}

sns/templates/sns/index.html
{% extends './base.html' %}
{% block content %}
<div class="contents">
  <div class="top-contents">
    <h1>あんにょん</h1>
    <div class="key-visual">
      <p>韓国語の本場の発音を学ぶ！</p>
      <p>友達を増やすにも最高の場となる。</p>
    </div>
  </div>
  <div class="content">
      <div>
          <h3>最新の記事</h3>
          {% for article in object_list %}
          <p class="topics">
            <a href="{% url 'view_article' article.pk %}">
              {{ article.title }}
            </a>
          </p>
          {% endfor %}
<!--            {% for article in articles %}-->
<!--              <a href="{% url 'view_article' article.pk %}" class=""><p class="topics">{{ article.title }}</p></a>-->
<!--            {% endfor %}-->
          <div>
            <a href="{% url 'article_all' %}" class="btn btn-border"><span>記事一覧へ</span></a>
          </div>
          <div>
            <a href="{% url 'new' %}" class="btn btn-border"><span>記事投稿へ</span></a>
          </div>
      </div>
  </div>
</div>
{% endblock %}

sns/templates/sns/new.html
{% extends './base.html' %}
{% block content %}
  <div class="create-contents">
    <h3>あんにょん</h3>
    <form action="" method="post">
        {% csrf_token %}
        <p><label for="title_input">title</label></p>
        <p><input type="text" name="title" id="title_input"></p>
        <p><label for="text_area">Text</label></p>
        <p><textarea name="text" id="text_area" cols="30" rows="10"></textarea></p>
        <p><button type="submit"> 投稿する</button></p>
    </form>
    <a href="{% url 'index' %}" class="btn btn-border"><span class="toppage">トップページへ</span></a>
  </div>
{% endblock %}

sns/templates/sns/view_article.html
{% extends 'layout.html' %}
{% block content %}

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.10.2/css/all.css">
    <div class="contents-article">
<!-------------------- content -------------------->
      <div class="content-article">
        <h3>{{ article.title }}</h3>
        <small>投稿日時 : {{ article.posted_at }}</small>
        <p class="content-text">{{ article.text }}</p>
        <a href="{% url 'edit' article.pk %}" class="btn btn-border"><span>編集</span></a>
        <a href="{% url 'delete' article.pk %}" class="btn btn-border"><span>削除</span></a>
        <p class="like"><a onclick="api_like()"><i class="fas fa-thumbs-up"></i><span id="like">{{ article.like }}</span></a></p>
      </div>
<!------------------ coment text ------------------->
      <form action="" method="POST">
          {% csrf_token %}
          <textarea name="text" id="com" cols="30" rows="10" placeholder="この記事にコメントする..."></textarea>
          <button type="submit"> - 投稿</button>
      </form>
      <a href="{% url 'index' %}" class="btn btn-border"><span>トップページへ</span></a>
      {% for comment in article.comments.all %}
          <p class="comments">{{ comment.text }}<br><small>{{ comment.posted_at }}</small></p>
      {% empty %}
      <p>コメントはありません</p>
      {% endfor %}
    </div>

    {% for book in books %}
            <div class="post">
            {% if book.image %}
            <div class ="image">
                <img src="/{{ book.image.url }}" style="width:300px;height:auto">
            </div>
            {% endif %}
                <div class="date">
                    {{ book.published_date }}
                </div>
                <h1><a href="{% url 'book_detail' pk=book.pk %}">{{ book.title }}</a></h1>
                <p>{{ book.link|linebreaksbr }}</p>
            </div>
    {% endfor %}
    <script>

        function api_like() {
            var api_url = "{% url 'api_like' article.pk %}";
            var btn = document.getElementById("like");
            var request = new XMLHttpRequest();
            request.onreadystatechange = function () {
                if (request.readyState === 4 && request.status === 200) {
                    var received_data = JSON.parse(request.responseText);
                    btn.innerText = received_data.like;
                }
            }
            request.open("GET",api_url);
            request.send();
        }
    </script>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
<head>
<meta charset="utf-8">
<title>あんにょん</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!--    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'>-->
<!--    <style>body {padding-top: 80px;}</style>-->
<link rel="stylesheet" href="{% static 'css/base.css' %}">
<link rel="stylesheet" href="{% static 'css/btn.css' %}">
<link rel="stylesheet" href="{% static 'css/topics.css' %}">
<link rel="stylesheet" href="{% static 'css/textbox.css' %}">
<link rel="stylesheet" href="{% static 'css/comment.css' %}">
</head>
<body>

<!--                    header                    -->

<div class='header'>
  <nav>
    <ul class="nav-items">
      <a href='{% url "index" %}' class="logo" ><h1>あんにょん</h1></a>
      {% if user.is_authenticated %}
      <li class="nav-item">
        <span class=''>{{ user }} - </span>
      </li>
      <li class="nav-item">
        <a href='{% url "logout" %}' class='logout'>Logout</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a href='{% url "login" %}' class='login'>Login</a>
      </li>
      <li class="nav-item">
        <a href='{% url "accounts:signup" %}' class='signup'>Sign up</a>
      </li>
      {% endif %}
    </ul>
  </nav>
</div>

<!--                    main                    -->

<div class="main">
  {% block content %}
  {% endblock %}
</div>

<!--                    footer                    -->

<div class="footer">
  <div class="container">
    <nav>
      <ul>
        <li><a href=""> - About</a></li>
        <li><a href=""> - Contact</a></li>
      </ul>
    </nav>
    <p>@2020 made in ShogoIkeda</p>
  </div>
</div>
</body>
</html>